// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../../packages/FSharp.Data/lib/net40/FSharp.Data.dll"
#r "../../../packages/FSharp.Text.RegexProvider/lib/net40/FSharp.Text.RegexProvider.dll"
#r "../../../packages/Http.fs/lib/net40/HttpClient.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "System.Xml.Linq.dll"
#r "../../../packages/FParsec/lib/net40-client/FParsec.dll"
#r "../../../packages/FParsec/lib/net40-client/FParsecCS.dll"
#r "../../../packages/FSharp.Control.AsyncSeq/lib/net45/FSharp.Control.AsyncSeq.dll"
#r "../../../packages/FSharpx.Async/lib/net40/FSharpx.Async.dll"
#r "../../../packages/FSharpx.Collections/lib/net40/FSharpx.Collections.dll"
#r "../../../packages/FSharpx.Extras/lib/40/FSharpx.Extras.dll"
#r "../../../packages/Suave/lib/net40/Suave.dll"
#r "../../../packages/Aether/lib/net35/Aether.dll"
#r "../../../packages/Chiron/lib/net40/Chiron.dll"