// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SlackTG")>]
[<assembly: AssemblyProductAttribute("SlackTG")>]
[<assembly: AssemblyDescriptionAttribute("A Slack slash command bot for querying the magic trading card game database")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SlackTG"
    let [<Literal>] AssemblyProduct = "SlackTG"
    let [<Literal>] AssemblyDescription = "A Slack slash command bot for querying the magic trading card game database"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
